
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-file-manager-cookbook
spec:
  schedule: "0 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: github-file-manager
            image: xorima/github-file-manager:0.2.1
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: xorimabot-github
                  key: github_token
            - name: GFM_SOURCE_REPO_OWNER
              value: sous-chefs
            - name: GFM_SOURCE_REPO_NAME
              value: repo-management
            - name: GFM_SOURCE_REPO_PATH
              value: "standardfiles/cookbook"
            - name: GFM_DESTINATION_REPO_OWNER
              value: sous-chefs
            - name: GFM_DESTINATION_REPO_TOPICS
              value: "chef-cookbook"
            - name: GFM_BRANCH_NAME
              value: "automated/standardfiles"
            - name: GFM_PULL_REQUEST_TITLE
              value: "Automated PR: Standardising Files"
            - name: GFM_PULL_REQUEST_BODY
              value: "This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management, this repo has been identified as a cookbook repo by topics of chef-cookbook"
            - name: GFM_GIT_NAME
              value: "Xorima Bot"
            - name: GFM_GIT_EMAIL
              value: "xorimabot@avon-lea.co.uk"
            - name: GFM_GIT_USERNAME
              value: "xorimabot"
          restartPolicy: Never